---
- hosts: all
  remote_user: root
  become: true
  become_user: root
  become_method: sudo
  tasks:
   - name: download ambari repo
     become: yes
     get_url: 
       url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.6.1.3/ambari.repo 
       dest: /etc/yum.repos.d/
       mode: 0755

   - name: ambari agent package installation
     yum:
      state: present
      name:
       - ambari-agent
 
   - name: Ambari Agent Configuration File Modification
     blockinfile:
       path: /etc/ambari-agent/conf/ambari-agent.ini
       insertafter: "security"
       content: |
          force_https_protocol=PROTOCOL_TLSv1_2
       backup: yes

   - name: Ambari replace configuration File Modification
     replace:
      path: /etc/ambari-agent/conf/ambari-agent.ini
      #regexp: "^hostname=localhost"
      #replace: "hostname={{ inventory_hostname }}"
      regexp: "hostname=localhost"
      replace: "hostname=sev01.asia-east1-b.c.xenon-broker-231307.internal"
      backup: yes

   - name: Python Configuration File Modification
     replace:
      path: /etc/python/cert-verification.cfg
      regexp: 'verify=platform_default'
      replace: 'verify=disable'
      backup: yes

   - name: Ensure ambari-agent is running
     service: name=ambari-agent state=started enabled=yes
